#!/bin/bash
export DISTRO_NAME="ubuntu";
echo "DISTRO_NAME=$DISTRO_NAME" >>  $GITHUB_ENV
export DISTRO_VERSION="18.04";
echo "DISTRO_VERSION=$DISTRO_VERSION" >>  $GITHUB_ENV
export DISTRO_VERSION_NAME="bionic"
echo "DISTRO_VERSION_NAME=$DISTRO_VERSION_NAME" >>  $GITHUB_ENV